### ISSUE TITLE
Labeling of Kernindikatoren Barcharts

### ISSUE THREAD

**Issue by AlexandraKapp** [technologiestiftung/bezirksregionenprofile_2_0#2]
[ ] name of BZR (Bezirksregion) in label instead of "BZR"
[ ] show absolute value of Berlin and BZR
![Bildschirmfoto 2019-10-29 um 11 07 22 AM](https://user-images.githubusercontent.com/18367515/67757540-4be82e80-fa3c-11e9-92d4-f11806cc9477.png)

**Comment by rgb3000** [comment]
ok I have added the values but as the numbers have no unit it's also hard to understand in my opinion
![2019-10-30_068 Bildschirmfoto](https://user-images.githubusercontent.com/5826403/67852997-cd5bc180-fb0d-11e9-9b06-ae0848ed95e5.png)
