### ISSUE TITLE
read "Datenquelle", "Datenstand", "Impressum", "Daten download" from overview json

### ISSUE THREAD

**Issue by AlexandraKapp** [technologiestiftung/bezirksregionenprofile_2_0#4]
read "Datenquelle", "Datenstand", "Impressum", "Daten download" from overview json

**Comment by rgb3000** [comment]
ok it works.
the fields 'imprint' and 'dataUrl' need to be added to `bzr-overview.json` files
'datenstand' need to be added to `bz-overview.json`
