### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by sebastian-meier** [technologiestiftung/bezirksregionenprofile_2_0#47]
What is the state of this project? Its currently live on netlify, but it is not further maintained. Can we archive this?

**Comment by bnjmnsbl** [comment]
@tori-d is still waiting for the district to approve this. 
(see: https://www.notion.so/citylabberlin/Bezirksregionenprofile-f982a1b8f36c4ccd96cee52a682fca32)
please don't archive yet
